[features]
seeds = false
[programs.localnet]
todo_app = "BudycRCKfrytu4vwrXxhAnJ7zo26RRjEijAodADTkmTV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/kenzy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000